# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MYSQL_CREATETBL.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(619, 633)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 0, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(490, 90, 112, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 130, 112, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(200, 110, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 80, 441, 521))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 270, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 370, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 320, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 470, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.t = QtWidgets.QLineEdit(self.frame)
        self.t.setGeometry(QtCore.QRect(180, 70, 221, 31))
        self.t.setObjectName("t")
        self.txtcolumn1name = QtWidgets.QLineEdit(self.frame)
        self.txtcolumn1name.setGeometry(QtCore.QRect(180, 120, 221, 31))
        self.txtcolumn1name.setObjectName("txtcolumn1name")
        self.txtcolumn2name = QtWidgets.QLineEdit(self.frame)
        self.txtcolumn2name.setGeometry(QtCore.QRect(180, 220, 221, 31))
        self.txtcolumn2name.setObjectName("txtcolumn2name")
        self.txtcolumn1type = QtWidgets.QLineEdit(self.frame)
        self.txtcolumn1type.setGeometry(QtCore.QRect(180, 170, 221, 31))
        self.txtcolumn1type.setObjectName("txtcolumn1type")
        self.txtcolumn3type = QtWidgets.QLineEdit(self.frame)
        self.txtcolumn3type.setGeometry(QtCore.QRect(180, 370, 221, 31))
        self.txtcolumn3type.setObjectName("txtcolumn3type")
        self.txtcolumn4name = QtWidgets.QLineEdit(self.frame)
        self.txtcolumn4name.setGeometry(QtCore.QRect(180, 420, 221, 31))
        self.txtcolumn4name.setObjectName("txtcolumn4name")
        self.txtcolumn3name = QtWidgets.QLineEdit(self.frame)
        self.txtcolumn3name.setGeometry(QtCore.QRect(180, 320, 221, 31))
        self.txtcolumn3name.setObjectName("txtcolumn3name")
        self.txtcolumn2type = QtWidgets.QLineEdit(self.frame)
        self.txtcolumn2type.setGeometry(QtCore.QRect(180, 270, 221, 31))
        self.txtcolumn2type.setObjectName("txtcolumn2type")
        self.txtcolumn4type = QtWidgets.QLineEdit(self.frame)
        self.txtcolumn4type.setGeometry(QtCore.QRect(180, 470, 221, 31))
        self.txtcolumn4type.setObjectName("txtcolumn4type")
        self.label_9.raise_()
        self.label_13.raise_()
        self.label_7.raise_()
        self.label_11.raise_()
        self.label_8.raise_()
        self.label_12.raise_()
        self.t.raise_()
        self.txtcolumn1name.raise_()
        self.txtcolumn2name.raise_()
        self.txtcolumn1type.raise_()
        self.txtcolumn3type.raise_()
        self.txtcolumn4name.raise_()
        self.txtcolumn3name.raise_()
        self.txtcolumn2type.raise_()
        self.txtcolumn4type.raise_()
        self.frame.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CREATING TABLE"))
        self.label_2.setText(_translate("Form", "DATABASE NAME: "))
        self.pushButton.setText(_translate("Form", "CREATE"))
        self.pushButton_2.setText(_translate("Form", "CANCEL"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">PYTHON</p></body></html>"))
        self.label_4.setText(_translate("Form", "TABLE NAME: "))
        self.label_5.setText(_translate("Form", "COLUMN 1 NAME:"))
        self.label_6.setText(_translate("Form", "COLUMN 1 TYPE:"))
        self.label_7.setText(_translate("Form", "COLUMN 2 TYPE:"))
        self.label_8.setText(_translate("Form", "COLUMN 2 NAME:"))
        self.label_12.setText(_translate("Form", "COLUMN 3 TYPE:"))
        self.label_9.setText(_translate("Form", "COLUMN 4 NAME:"))
        self.label_11.setText(_translate("Form", "COLUMN 3 NAME:"))
        self.label_13.setText(_translate("Form", "COLUMN 4 TYPE:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
