# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MYSQL_UPDATE.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MYSQL_UPDATE(object):
    def setupUi(self, MYSQL_UPDATE):
        MYSQL_UPDATE.setObjectName("MYSQL_UPDATE")
        MYSQL_UPDATE.resize(754, 488)
        self.label_4 = QtWidgets.QLabel(MYSQL_UPDATE)
        self.label_4.setGeometry(QtCore.QRect(40, 190, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnupdate = QtWidgets.QPushButton(MYSQL_UPDATE)
        self.btnupdate.setGeometry(QtCore.QRect(620, 130, 112, 32))
        self.btnupdate.setObjectName("btnupdate")
        self.label_7 = QtWidgets.QLabel(MYSQL_UPDATE)
        self.label_7.setGeometry(QtCore.QRect(40, 290, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txtvalue3 = QtWidgets.QLineEdit(MYSQL_UPDATE)
        self.txtvalue3.setGeometry(QtCore.QRect(210, 340, 221, 31))
        self.txtvalue3.setObjectName("txtvalue3")
        self.txttblname = QtWidgets.QLineEdit(MYSQL_UPDATE)
        self.txttblname.setGeometry(QtCore.QRect(210, 190, 221, 31))
        self.txttblname.setObjectName("txttblname")
        self.label_3 = QtWidgets.QLabel(MYSQL_UPDATE)
        self.label_3.setGeometry(QtCore.QRect(210, 140, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(MYSQL_UPDATE)
        self.label.setGeometry(QtCore.QRect(120, 20, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtvalue2 = QtWidgets.QLineEdit(MYSQL_UPDATE)
        self.txtvalue2.setGeometry(QtCore.QRect(210, 290, 221, 31))
        self.txtvalue2.setObjectName("txtvalue2")
        self.label_2 = QtWidgets.QLabel(MYSQL_UPDATE)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(MYSQL_UPDATE)
        self.label_9.setGeometry(QtCore.QRect(40, 390, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(MYSQL_UPDATE)
        self.label_5.setGeometry(QtCore.QRect(40, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtvalue1 = QtWidgets.QLineEdit(MYSQL_UPDATE)
        self.txtvalue1.setGeometry(QtCore.QRect(210, 240, 221, 31))
        self.txtvalue1.setObjectName("txtvalue1")
        self.frame = QtWidgets.QFrame(MYSQL_UPDATE)
        self.frame.setGeometry(QtCore.QRect(20, 120, 591, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.primkey1 = QtWidgets.QCheckBox(self.frame)
        self.primkey1.setGeometry(QtCore.QRect(440, 120, 101, 31))
        self.primkey1.setObjectName("primkey1")
        self.primkey3 = QtWidgets.QCheckBox(self.frame)
        self.primkey3.setGeometry(QtCore.QRect(440, 220, 101, 31))
        self.primkey3.setObjectName("primkey3")
        self.primkey2 = QtWidgets.QCheckBox(self.frame)
        self.primkey2.setGeometry(QtCore.QRect(440, 170, 101, 31))
        self.primkey2.setObjectName("primkey2")
        self.primkey4 = QtWidgets.QCheckBox(self.frame)
        self.primkey4.setGeometry(QtCore.QRect(440, 270, 101, 31))
        self.primkey4.setObjectName("primkey4")
        self.primkey3.raise_()
        self.primkey2.raise_()
        self.primkey1.raise_()
        self.primkey4.raise_()
        self.btncancel = QtWidgets.QPushButton(MYSQL_UPDATE)
        self.btncancel.setGeometry(QtCore.QRect(620, 160, 112, 32))
        self.btncancel.setObjectName("btncancel")
        self.label_6 = QtWidgets.QLabel(MYSQL_UPDATE)
        self.label_6.setGeometry(QtCore.QRect(40, 340, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.txtvalue4 = QtWidgets.QLineEdit(MYSQL_UPDATE)
        self.txtvalue4.setGeometry(QtCore.QRect(210, 390, 221, 31))
        self.txtvalue4.setObjectName("txtvalue4")
        self.frame.raise_()
        self.btnupdate.raise_()
        self.label.raise_()
        self.btncancel.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.txtvalue2.raise_()
        self.txtvalue3.raise_()
        self.txtvalue1.raise_()
        self.txtvalue4.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.txttblname.raise_()
        self.label_9.raise_()
        self.label_2.raise_()
        self.label_7.raise_()

        self.retranslateUi(MYSQL_UPDATE)
        QtCore.QMetaObject.connectSlotsByName(MYSQL_UPDATE)

    def retranslateUi(self, MYSQL_UPDATE):
        _translate = QtCore.QCoreApplication.translate
        MYSQL_UPDATE.setWindowTitle(_translate("MYSQL_UPDATE", "Form"))
        self.label_4.setText(_translate("MYSQL_UPDATE", "TABLE NAME: "))
        self.btnupdate.setText(_translate("MYSQL_UPDATE", "UPDATE"))
        self.label_7.setText(_translate("MYSQL_UPDATE", "NEW VALUE 2:"))
        self.label_3.setText(_translate("MYSQL_UPDATE", "<html><head/><body><p align=\"center\">PYTHON</p></body></html>"))
        self.label.setText(_translate("MYSQL_UPDATE", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">UPDATING VALUES IN TABLE</span></p></body></html>"))
        self.label_2.setText(_translate("MYSQL_UPDATE", "DATABASE NAME: "))
        self.label_9.setText(_translate("MYSQL_UPDATE", "NEW VALUE 4:"))
        self.label_5.setText(_translate("MYSQL_UPDATE", "NEW VALUE 1: "))
        self.primkey1.setText(_translate("MYSQL_UPDATE", "primary key"))
        self.primkey3.setText(_translate("MYSQL_UPDATE", "primary key"))
        self.primkey2.setText(_translate("MYSQL_UPDATE", "primary key"))
        self.primkey4.setText(_translate("MYSQL_UPDATE", "primary key"))
        self.btncancel.setText(_translate("MYSQL_UPDATE", "CANCEL"))
        self.label_6.setText(_translate("MYSQL_UPDATE", "NEW VALUE 3: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MYSQL_UPDATE = QtWidgets.QWidget()
    ui = Ui_MYSQL_UPDATE()
    ui.setupUi(MYSQL_UPDATE)
    MYSQL_UPDATE.show()
    sys.exit(app.exec_())
